config/routes.rb
Syncline::Application.routes.draw do

  get "site_users/create"
  get "site_users/new"
  get "site_users/edit"
  get "site_users/destroy"
  resources :field_tests, only: [:new, :create, :update, :destroy]
  resources :lab_tests, only: [:new, :create, :update, :destroy]
  resources :sites, only: [:index, :show, :create] do
    resources :drill_holes do
      resources :layers
    end
    resources :projects, only: [:index]
  end

  resources :site_users, only: [:new, :create]
  resource :session, only: [:create, :destroy, :index, :new]
  resources :users, only: [:new, :show, :create, :edit, :destroy]

  get '/sites/:id/layers', to: 'layers#site_layers'
  get '/sites/:id/details', to: 'sites#details'
  put '/drill_hole/:id/update_reviewer', to: 'drill_holes#update_reviewer'
  put '/layers/sort', to: 'layers#sort'
  root to: 'sessions#index'

end

app/models/drill_hole.rb
class DrillHole < ActiveRecord::Base

  default_scope { order('id') }

  belongs_to :site
  has_many :layers, dependent: :destroy

  validates :site_id,
    presence: true
  validates :logged_by,
    presence: true
  validates :logged_by_id,
    presence: true
  validates :name,
    presence: true
  validates :depth,
    presence: true
  validates :ground_elev,
    presence: true
  validates :dh_lat,
      presence: true, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }
  validates :dh_lng,
      presence: true, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }

  validate :check_logged_by_and_reviewed_by

  def check_logged_by_and_reviewed_by
    errors.add(:reviewed_by, "can't be the same as logger") if logged_by_id == reviewed_by_id
  end
end

app/models/field_test.rb
class FieldTest < ActiveRecord::Base
  belongs_to :layer
  has_many :spts, dependent: :destroy
  has_many :photos, dependent: :destroy
end

app/models/grain_size.rb
class GrainSize < ActiveRecord::Base
  belongs_to :lab_test
end

app/models/lab_test.rb
class LabTest < ActiveRecord::Base
  belongs_to :field_test
  has_many :grain_sizes, dependent: :destroy
  has_many :photos, dependent: :destroy
end

app/models/layer.rb
class Layer < ActiveRecord::Base
  belongs_to :material_type
  belongs_to :drill_hole
  has_many :field_tests, dependent: :destroy

  default_scope { order('date_drilled') }

  scope :layer_thickness, -> (drill_hole_id, material_type_name) do
    where(drill_hole_id: drill_hole_id, material_type_id: MaterialType.where(name: material_type_name).pluck(:id)).sum(:thickness)
  end

  scope :depth_drilled_by_date, -> (site_id) do
    where(:drill_hole_id => DrillHole.where(site_id: site_id).select("id")).select("date_drilled, sum(thickness) as total_thickness").group(:date_drilled)
  end

  def round_thickness
    thickness.round(2)
  end
end

app/models/material_type.rb
class MaterialType < ActiveRecord::Base
  has_many :layers
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :field_test
  belongs_to :lab_test
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :drill_holes, dependent: :destroy
  has_many :site_users, dependent: :destroy

  validates :site_name,
      presence: true

  validates :center_lat,
      presence: true, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }

  validates :center_lng,
      presence: true, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
end

app/models/site_user.rb
class SiteUser < ActiveRecord::Base
  belongs_to :site
  belongs_to :user
end

app/models/spt.rb
class Spt < ActiveRecord::Base
  belongs_to :field_test
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email,
    presence: true

  validates :first_name,
      presence: true

  validates :last_name,
      presence: true

  scope :site_users, -> (site_id) do
    where(:id => SiteUser.where(site_id: site_id).pluck(:user_id))
  end

  def name
    first_name + ' ' + last_name
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def require_logged_in_user
    unless current_user
      flash[:error] = "You must be logged in to see your sites"
      redirect_to root_path
    end
  end

  def is_a_site_user
    if SiteUser.where("user_id = ? AND site_id = ?", current_user.id, current_site).count < 1
      p "hello"
      flash[:error] = "You must be authorized to see this site"
      redirect_to root_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_site
    session[:site_id]
  end

  def current_layer
    session[:layer_id]
  end

  def current_field_test
    session[:field_test_id]
  end

  def current_lab_test
    session[:lab_test_id]
  end

end

app/helpers/drill_holes_helper.rb
module DrillHolesHelper
end

app/helpers/field_tests_helper.rb
module FieldTestsHelper
end

app/helpers/lab_tests_helper.rb
module LabTestsHelper
end

app/helpers/layers_helper.rb
module LayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_users_helper.rb
module SiteUsersHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Syncline</title>
  <link href='https://api.mapbox.com/mapbox.js/v2.3.0/mapbox.css' rel='stylesheet' />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body class='theme-1'>
<%= render 'layouts/partials/nav_bar' unless @disable_nav%>

<!-- render hero if front page? -->
<div class="flash">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "notification") %>
  <% end %>
</div>


<section id="section-container" class="section page-content">
  <%= yield %>
</section>




<%= render 'layouts/partials/footer' %>

<script src="http://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src='https://api.mapbox.com/mapbox.js/v2.3.0/mapbox.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.min.js'></script>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/layouts/partials/_footer.html.erb
<footer class="footer site-footer">
  <div class="container">
    <div class="content is-centered">
      <div class="container">
        <img class='footer-logo' src="/assets/full-syncline-logo-small.png">
        <p class=footer-text>
          A tool aimed at geotechnical engineers to streamline the process of collecting, reviewing and approving site investigation information.
          <br>
          <strong>Built with Rails, JavaScript, HTML5, CSS3, JQuery, PostgreSQL, HighCharts and Mapbox by:</strong>
        </p>

        <div class="container is-flex">
          <a class="button" href="https://github.com/joelkbennett">
            <i class="fa fa-github"></i>
            joelkbennett
          </a>
          <a class="button" href="https://github.com/PrabhBrar">
            <i class="fa fa-github"></i>
            PrabhBrar
          </a>
          <a class="button" href="https://github.com/quicklikerabbit">
            <i class="fa fa-github"></i>
            quicklikerabbit
          </a>
          <a class="button" href= "https://github.com/scottcaldwell">
            <i class="fa fa-github"></i>
            scottcaldwell
          </a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/partials/_nav_bar.html.erb
<header class='site-header'>

  <!-- Main container -->
  <nav class="navbar">
    <!-- Left side -->
    <div class="navbar-left">

      <div class="navbar-item">
        <a href='/'><img class='site-logo' src="/assets/full-syncline-logo-small.png"></a>
        <!-- <a href='/'><img class='site-logo' src="/assets/syncline-logo-small.png"></a> -->
        <!-- <h1 class="site-title">Syncline</h1> -->
      </div>
      <div class="navbar-item">
        <%= link_to "All Sites", sites_path, :class => "button is-primary is-outlined is-inverted" %>
      </div>

    </div>

    <!-- Right side -->
    <div class="navbar-right">
      <% if current_user %>
        <p class="navbar-item"><a href="#">Hey, <%= current_user.first_name %> </a></p><i class="fa fa-user nav-icon"></i>
        <p class="navbar-item"><%= link_to "Log out", session_path("current"), method: :delete %>  </p><i class="fa fa-sign-out nav-icon"></i>
      <% else %>
        <p class="navbar-item"><%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %></p><i class="fa fa-sign-in nav-icon"></i>
      <% end %>
    </div>
  </nav>

</header>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "application", :media => 'all' %>
</head>
<body>
  <div class="section page-content">
    <%= yield %>
  </div>
  <%= wicked_pdf_javascript_include_tag "http://code.jquery.com/jquery-1.10.0.min.js" %>
  <%= wicked_pdf_javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.min.js" %>
  <%= wicked_pdf_javascript_include_tag "layers_pdf" %>
</body>
</html>