config/routes.rb
Syncline::Application.routes.draw do

  get "site_users/create"
  get "site_users/new"
  get "site_users/edit"
  get "site_users/destroy"
  resources :field_tests, only: [:new, :create, :update, :destroy]
  resources :lab_tests, only: [:new, :create, :update, :destroy]
  resources :sites, only: [:index, :show, :create] do
    resources :drill_holes do
      resources :layers
    end
    resources :projects, only: [:index]
  end

  resources :site_users, only: [:new, :create]
  resource :session, only: [:create, :destroy, :index, :new]
  resources :users, only: [:new, :show, :create, :edit, :destroy]

  get '/sites/:id/layers', to: 'layers#site_layers'
  get '/sites/:id/details', to: 'sites#details'
  put '/drill_hole/:id/update_reviewer', to: 'drill_holes#update_reviewer'
  put '/layers/sort', to: 'layers#sort'
  root to: 'sessions#index'

end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :drill_holes, dependent: :destroy
  has_many :site_users, dependent: :destroy

  validates :site_name,
      presence: true

  validates :center_lat,
      presence: true, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }

  validates :center_lng,
      presence: true, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  include ApplicationHelper

  before_action :require_logged_in_user

  respond_to :html, :js

  def index
    @users_sites = SiteUser.where(user_id: current_user.id).pluck(:site_id)
    @sites = Site.where(id: @users_sites).order(created_at: :desc)
    @site = Site.new
  end

  def show
    @site_id = params[:id]
    @site = Site.find(@site_id)
    @drill_holes = DrillHole.where(site_id: @site_id)
    @drill_hole = DrillHole.new
    @user_credentials = current_user.first_name[0] + current_user.last_name[0]
    @site_users = User.site_users(@site_id)
    if @drill_holes.length > 0
      @latest_dh_name = @drill_holes.last.name
      @new_dh_name = (@latest_dh_name.scan(/(.+-)/).flatten + (@latest_dh_name.scan(/(\d+$)/).flatten.map{ |ele| ele.to_i + 1})).join("")
    else
      @new_dh_name = ''
    end
    session[:site_id] = @site_id
    is_a_site_user
  end

  def create
    @site  = Site.new(site_params)
    if @site.save
      @site_user = SiteUser.create(site_id: @site.id, user_id: current_user.id, admin: true)
    else
      flash[:error] = "Site not saved, verify your data."
    end
    redirect_to :back
  end

  def details
    @siteDetails = Site.where(id: params[:id]).select("drill_by_date, drill_to_depth")
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @siteDetails }
    end
  end

  protected

  def site_params
    # params.require(:site).permit()
    params.require(:site).permit(:site_name, :center_lat, :center_lng, :drill_to_depth, :drill_by_date)
  end

end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/index.html.erb
<article class='page-body content'>

  <header class='page-header'>
    <div class="container">
      <div class='heading'>
        <h1 class='title is-1'>My Sites</h1>
      </div>
    </div>
  </header>
  <section class='section'>

      <div class="container">
      <a class="button is-large" id="add-site-button" style="margin-left: 2px"><i class="fa fa-plus"></i>&nbsp; Add new Site</a>

      <div class="columns sites-columns">
        <% @sites.each do |site| %>

          <div class="column is-third-tablet is-third-desktop drill-card">
            <a id="site-link" href='<%= site_path(site.id)%>'>
              <div class="card">
                <div class="card-image">
                </div>
                <div class="card-content static-map is-flex" >
                  <div class="site-info is-info">
                    <p id="site-title"><%= site.site_name %></p>
                    <small="info"><strong><%= site.created_at%></strong></small></br>
                    <small class="site-lat info" data-site-lat="<%= site.center_lat %>"><strong>Lat: <%= number_with_precision(site.center_lat, precision: 3) %></strong></small>
                    <small class="site-lng info" data-site-lng="<%= site.center_lng %>"><strong>Lng: <%= number_with_precision(site.center_lng, precision: 3) %></strong></small>
                  </br><small class="info"><strong>Drill Holes: <%= site.drill_holes.count %></strong></small>
                  </div>
                </div>
              </div>
            </a>
          </div>
        <% end %>

        <!-- <div class="column is-third-tablet is-third-desktop new-site">
          <div class="new-site-card" id="new-site-card">
            <div class="add-site"> -->
            <!-- </div>
          </div>
        </div> -->

        <div class="modal" id="add-site-modal">
          <div class="modal-background"></div>
          <div class="modal-content">
            <div class="box">
              <div class="content">
                <div>
                  <h1>Select site from map, or enter manually</h1>
                  <p class="control">
                    <%= form_for @site, html: { class: 'columns' } do |f|%>
                      <div class="column is-half-tablet is-half-desktop">
                        <p class="columns">
                          <%= f.label 'Site Name:', :class => "label column is-3" %><br />
                          <%= f.text_field :site_name, :class => 'input column is-8 is-medium input-locked', required: true%>
                        </p>
                        <p class="columns latitude-input">
                          <%= f.label 'Latitude: ', :class => "label column is-3" %><br />
                          <%= f.text_field :center_lat, :class => 'input column is-8 is-medium input-locked', required: true %>
                          <span id="latitude-helper">Enter Valid Latitude</span>
                        </p>
                        <p class="columns longitude-input">
                          <%= f.label 'Longitude: ', :class => "label column is-3" %><br />
                          <%= f.text_field :center_lng, :class => 'input column is-8 is-medium input-locked', required: true %>
                          <span id="longitude-helper">Enter Valid Longitude</span>
                        </p>
                      </div>
                      <div class="column is-half-tablet is-half-desktop">
                        <p class="columns">
                          <%= f.label 'Expected completion date:', :class => "label column is-5" %><br />
                          <%= f.date_field :drill_by_date, :class => 'input column is-6 is-medium input-locked' %>
                        </p>
                        <p class="columns">
                          <%= f.label 'Expected meters drilled:', :class => "label column is-5" %><br />
                          <%= f.text_field :drill_to_depth, :class => 'input column is-6 is-medium input-locked' %>
                        </p>
                        <p class="site-submit-button" id="site-submit-button">
                          <%= f.submit 'Create New Site', :class => 'button is-primary' %>
                        </p>
                      </div>
                    <% end %>
                  </p>
                  <div id="geo-search-map" class='map'></div>
                </div>
              </div>
            </div>
            <button class="modal-close" id="site-modal"></button>
          </div>
        </div>
    </div>
  </section>

</article>

app/views/sites/show.html.erb
<article class='page-body content'>
  <header class='site-overview-header'>
    <div class="container">
      <div class='heading'>
        <h1 class='title is-1'><%= @site.site_name %></h1>
      </div>
    </div>
  </header>

  <section class='section site-overview'>
      <div id='markers-map' class='map'></div>
  </section>
  <section>
    <div class="modal" id="add-new-drill-hole-modal">
      <div class="modal-background"></div>
      <div class="modal-content">
        <div class="box">
          <div class="content">
            <div>
              <h1>Select drill hole location from map, or enter manually</h1>
              <p class="control">
                <%= form_for @drill_hole, url: site_drill_holes_path(@site.id), method: :post, html: { class: 'columns' } do |f|%>
                  <div class="column is-half-tablet is-half-desktop">
                    <p class="control columns">
                      <label class="label column is-3">Name:</label>
                      <%= f.text_field :name, value: @new_dh_name, class: 'input column is-8 is-medium input-locked', required: true %>
                    </p>
                    <p class="control columns">
                      <label class="label column is-3">Logged by:</label>
                      <%= f.text_field :logged_by, value: @user_credentials, class: 'input column is-8 is-medium input-locked', required: true %>
                    </p>

                    <p class="control columns latitude-input">
                      <label class='label column is-3'>Latitude:</label>
                      <%= f.text_field :dh_lat, class: 'input column is-8 is-medium input-locked', required: true %>
                      <span id="latitude-helper">Enter Valid Latitude</span>
                    </p>

                    <p class="control columns longitude-input">
                      <label class="label column is-3">Longitude:</label>
                      <%= f.text_field :dh_lng, class: 'input column is-8 is-medium input-locked', required: true %>
                      <span id="longitude-helper">Enter Valid Longitude</span>
                    </p>

                    <p class="control columns">
                      <label class="label column is-3">Ground Elevation:</label>
                      <%= f.number_field :ground_elev, class: 'input column is-8 is-medium input-locked', required: true %>
                    </p>

                    <p class="control columns">
                      <label class="label column is-3">Depth:</label>
                      <%= f.number_field :depth, class: 'input column is-8 is-medium input-locked', required: true %>
                    </p>

                  </div>

                  <div class="column is-half-tablet is-half-desktop">
                    Water Level
                    <div class="water-level container">
                      <p class="control columns">
                        <label class="label column is-3">Start:</label>
                        <%= f.number_field :water_level_start, class: 'input column is-8 is-medium input-locked' %>
                      </p>

                      <p class="control columns">
                        <label class="label column is-3">During:</label>
                        <%= f.number_field :water_level_during, class: 'input column is-8 is-medium input-locked' %>
                      </p>

                      <p class="control columns">
                        <label class="label column is-3">End:</label>
                        <%= f.number_field :water_level_end, class: 'input column is-8 is-medium input-locked' %>
                      </p>
                    </div>

                    <p class="control columns">
                      <label class="label column is-3">Hole Size:</label>
                      <%= f.number_field :hole_size, class: 'input column is-8 is-medium input-locked', step: '0.01' %>
                    </p>

                    <p class="control columns">
                      <label class="label column is-3">Method:</label>
                      <%= f.text_field :method, class: 'input column is-8 is-medium input-locked' %>
                    </p>

                    <p class="control dh-submit-button" id="dh-submit-button">
                      <%= f.submit "Add Drill Hole", class: 'button is-primary' %>
                    </p>
                  </div>
                <% end %>
              </p>
              <div id="drill-hole-geo-search-map" class='map'></div>
            </div>
          </div>
        </div>
        <button class="modal-close" id="dh-modal"></button>
      </div>
    </div>
  </section>
<section>
  <div class="modal" id="add-user-to-site-modal">
    <div class="modal-background"></div>
    <div class="modal-content">
      <div class="box">
        <div class="content">
          <div>
            <h1>Add a someone to this site by their email address</h1>
            <p class="control">
              <%= form_tag site_users_path do %>
                <div class="columns">
                  <div class="column is-third-tablet is-half-desktop">
                    <p class="control has-icon">
                      <input class="input" name="user[email]" type="email" placeholder="Email">
                      <i class="fa fa-envelope"></i>
                    </p>
                    <p class="control">
                      <button class="button is-success">
                        Submit
                      </button>
                    </p>
                  </div>
                </div>
              <% end %>
            </p>
          </div>
        </div>
      </div>
      <button class="modal-close" id="add-user-modal"></button>
    </div>
  </div>
</section>

  <section class='section site-charts'>
    <div class="container">
          <a class="button is-medium" id="add-new-drill-hole-button" style="margin-left: 2px"><i class="fa fa-plus"></i>&nbsp; Add new Drill Hole</a>
          <a class="button is-medium" id="add-user-button"><i class="fa fa-user-plus"></i>&nbsp; Add User to Site</a>
          <br><br>
      <div class="columns">
        <div class="column" id="project-details" style="min-width: 310px; height: 400px; margin: 0 auto" data-site="<%= @site.to_json %>"></div>
        <div class="column" id="material-details" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
      </div>
    </div>
  </section>

  <section class='section drill-holes-table'>
    <div class="container">
      <div class="table-wrap">
        <h1>Drill Holes</h1>
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Depth</th>
              <th>Location</th>
              <th>Latitude</th>
              <th>Longitude</th>
              <th></th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>Name</th>
              <th>Depth</th>
              <th>Location</th>
              <th>Latitude</th>
              <th>Longitude</th>
              <th></th>
            </tr>
          </tfoot>
          <tbody>
            <% @drill_holes.each do |drill_hole| %>
              <tr class="drill-row" data-dh-details="<%= { drill_hole: drill_hole }.to_json %>">
                <td><%= drill_hole.name %></td>
                <td><%= number_with_precision(drill_hole.depth, precision: 2) %></td>
                <td><%= @site.site_name %></td>
                <td><%= number_with_precision(drill_hole.dh_lat, precision: 7) %></td>
                <td><%= number_with_precision(drill_hole.dh_lng, precision: 7) %></td>
                <td><%= link_to "View", site_drill_hole_path(@site.id, drill_hole.id), :class => "button is-primary" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </section>

  <section class='section site_user-table'>
    <div class="container">
      <div class="table-wrap">
        <h1>Site Users</h1>
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
            </tr>
          </thead>
          <tbody>
            <% @site_users.each do |site_user| %>
              <tr>
                <td><%= site_user.name %></td>
                <td><%= site_user.email %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </section>
</article>